/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alitransport;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Haider Ali
 */
public class customer extends javax.swing.JFrame {

    /**
     * Creates new form customer
     */
     Statement stmnt=null;
    ResultSet r=null;
    PreparedStatement p=null;
    Connection con=null;
    public customer() {
        initComponents();
        con=AliTransport.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("            CUSTOMER      INFO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 60, 300, 40);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButton1.setText("SIGN  IN");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(323, 132, 95, 27);

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 0, 0));
        jRadioButton2.setText("SIGN  UP");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(592, 132, 97, 27);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("  CUSTOMER  ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(323, 206, 150, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("  CUSTOMER NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(323, 249, 150, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("  ADDRESS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(323, 287, 150, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("  CONTACT");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(323, 330, 150, 25);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(539, 206, 150, 22);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(539, 249, 150, 22);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(539, 287, 150, 22);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(539, 330, 150, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("SAVE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(402, 407, 71, 27);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("EXIT");
        getContentPane().add(jButton2);
        jButton2.setBounds(592, 407, 67, 27);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Haider Ali\\Desktop\\customer.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
         if(jRadioButton2.isSelected())
      { 
          String query = "insert into customer (cid,cname,caddress,contact) values(?,?,?,?)";
      try{
          p=con.prepareStatement(query);
          p.setString(1,jTextField1.getText());
          p.setString(2,jTextField2.getText());
          p.setString(3,jTextField3.getText());
          p.setString(4,jTextField4.getText());
          p.executeUpdate();
           p.close();
           
         } 
      catch (SQLException ex) 
      {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
      }
      JOptionPane.showMessageDialog(null,"CUSTOMER IS ADDED");
       
      }
         
      if(jRadioButton1.isSelected())
      {
          String query="select trim(cid) as cid, trim(cname) as cname , trim(caddress) as caddress, trim(contact) as contact from customer where cid='" + jTextField1.getText() + "'";
          try {
              p=con.prepareStatement(query);
              r=p.executeQuery();
              while(r.next())
              {
                  if(r.getString("cid").equals(jTextField1.getText()))
                  { if(r.getString("cname").equals(jTextField2.getText()))
                    {      if(r.getString("caddress").equals(jTextField3.getText()))
                           {   if(r.getString("contact").equals(jTextField4.getText()))
                               {
                                   JOptionPane.showMessageDialog(null,"Signed In Successfully");
                                   JOptionPane.showMessageDialog(null,"Go For Booking");
                                    Vehicletransport trans=new Vehicletransport();
                                    trans.setVisible(true);
                                    customer cust=new customer();
                                    cust.setVisible(false);
                                    expenses.id=r.getString("cid");
                                    expenses.contact=r.getString("contact");
                               }
                               else
                               JOptionPane.showMessageDialog(null,"Incorrect Details");
                           }
                            else
                           JOptionPane.showMessageDialog(null,"Incorrect Details");
                     }
                     else
                     JOptionPane.showMessageDialog(null,"Incorrect Details");
                   }
                  else
                  JOptionPane.showMessageDialog(null,"Incorrect Details");
               }
               
              p.close();
              r.close();
          } catch (SQLException ex) {
              Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
          }
          
           
      }    
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JRadioButton jRadioButton1;
    public javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
