/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alitransport;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Haider Ali
 */
public class expenses extends javax.swing.JFrame {

   public static String id=null;

    /**
     *
     */
    public static String contact=null;

   

    /**
     * Creates new form transport
     */
     Statement stmnt=null;
    ResultSet r=null;
    PreparedStatement p=null;
    Connection con=null;
    public expenses() {
        initComponents();
        con=AliTransport.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        setFocusableWindowState(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("  SOURCE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(298, 235, 150, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 153));
        jLabel2.setText("  DESTINATION");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(298, 286, 150, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 153));
        jLabel3.setText("  DISTANCE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(298, 350, 150, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 153));
        jLabel4.setText("  COST/UNIT");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(298, 402, 150, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 153));
        jLabel5.setText("  TOLL TAX");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(298, 453, 150, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 153));
        jLabel6.setText("  DIESEL PETROL");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(298, 505, 150, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 153));
        jLabel7.setText(" DRIVER ALLOWANCE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(298, 554, 163, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 153));
        jLabel8.setText("  MAXM LOAD");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(298, 606, 150, 25);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT SOURCE", "Delhi", "Noida", "Gurgaon", "Pune", "Chandigarh", "Mumbai", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(710, 236, 200, 25);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT  DESTINATION", "Delhi", "Noida", "Gurgaon", "Pune", "Chandigarh", "Mumbai", " " }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(710, 287, 200, 25);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(710, 351, 150, 25);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(710, 403, 150, 25);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(710, 454, 150, 25);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(710, 506, 150, 25);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(710, 555, 150, 25);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(708, 607, 150, 25);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 153));
        jButton1.setText("SAVE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(500, 666, 71, 27);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 153));
        jButton2.setText("EXIT");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(708, 666, 67, 27);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 153));
        jLabel9.setText("  SERVICE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(298, 191, 150, 25);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT SERVICE NAME", "Hindustan Express Packers & Movers", "Mouvement Logistics Private Ltd", "Bombay South Cargo Packers & Movers", "Gjrat Transport Serivce", "National Packers & Movers ", "Baby Tempo Transport Service", "Reliable Cargo Movers & Packers,Delhi", "Globe Golden Transport", "Sankarshan Logistics Solution", "Balaji Packers & Movers", "Sharda Packers & Movers", "Sankarshan Logistics Solution" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(710, 192, 200, 25);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 153));
        jLabel10.setText("  DATE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(298, 139, 150, 25);

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(255, 0, 153));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DD", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(654, 138, 70, 25);

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(255, 0, 153));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MM", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(760, 140, 70, 25);

        jComboBox6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jComboBox6.setForeground(new java.awt.Color(255, 0, 153));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YY", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(860, 140, 70, 25);

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("(approx)");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(898, 355, 49, 16);

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("(approx)");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(898, 407, 49, 16);

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("(approx)");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(898, 458, 49, 16);

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("(approx)");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(898, 510, 49, 16);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        jLabel16.setText(" EXPENSES  INFO");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(80, 16, 330, 60);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Haider Ali\\Desktop\\vehicles.jpg")); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
         Login lo=new Login();
         lo.setVisible(true);
         expenses exp=new expenses();
         exp.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String query="insert into booking(day,month,year,service,source,destination,cid,contact) values(?,?,?,?,?,?,?,?)"; 
           try {
              p=con.prepareStatement(query);
              p.setInt(1,Integer.parseInt(jComboBox4.getItemAt(jComboBox4.getSelectedIndex())));
              p.setInt(2,Integer.parseInt(jComboBox5.getItemAt(jComboBox5.getSelectedIndex())));
              p.setInt(3,Integer.parseInt(jComboBox6.getItemAt(jComboBox6.getSelectedIndex())));
              p.setString(4,jComboBox3.getItemAt(jComboBox3.getSelectedIndex()));
              p.setString(5,jComboBox1.getItemAt(jComboBox1.getSelectedIndex()));
              p.setString(6,jComboBox2.getItemAt(jComboBox2.getSelectedIndex()));
              p.setString(7,id);
              p.setString(8,contact);
              p.executeUpdate();
              p.close();
          }
          catch (SQLException ex) {
              Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
          }
            JOptionPane.showMessageDialog(null,"BOOKING IS SUCCESSFULL");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        String source=jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
         String destination=jComboBox2.getItemAt(jComboBox2.getSelectedIndex());
         String sqlquery="select cost,maxm_load from Vehicletransport where service='"+ jComboBox3.getItemAt(jComboBox3.getSelectedIndex()) +"'";
          try {
              p=con.prepareStatement(sqlquery);
              r=p.executeQuery();
              while(r.next())
              {  
                  jTextField2.setText(r.getString("cost"));
                  jTextField6.setText(r.getString("maxm_load"));
              }
          }
          catch (SQLException ex) {
              Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
          }
          
          String sqlquery2="select trim(distance) as distance, trim(toll) as toll,  trim(diesel) as diesel, trim(allowance) as allowance from expenses where route='"+ source+destination +"'";
           try {
              p=con.prepareStatement(sqlquery2);
              r=p.executeQuery();
              while(r.next())
              {  
                   jTextField1.setText(r.getString("distance")); 
                   jTextField3.setText(r.getString("toll"));
                   jTextField4.setText(r.getString("diesel"));
                   jTextField5.setText(r.getString("allowance"));
                 
              }
          }
          catch (SQLException ex) {
              Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(expenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(expenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(expenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(expenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new expenses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    public static javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
